### ISSUE TITLE
Use dotenv to load environment variables on development and test

### ISSUE THREAD

**Issue by vitortalaia** [andrew/contribulator#233]
I noticed that currently the project needs the `OCTOKIT_TOKEN` variable to work properly (I mean, with a higher rate limit on GitHub API requests). I think it'd be nice if we had a `.env.example` file on the root directory that contributors can use to generate their own `.env` files.

What are your thoughts about it?

**Comment by andrew** [comment]
Yeah that's awesome, I'm using dotenv on https://github.com/librariesio/libraries.io already, works really well 👍
