### ISSUE TITLE
omniauth fails with 404

### ISSUE THREAD

**Issue by wadtech** [andrew/contribulator#37]
The callback redirected URL looks like: https://contribulator.herokuapp.com/auth/failure?message=redirect_uri_mismatch&origin=http%3A%2F%2Fcontribulator.herokuapp.com%2Fwadtech&strategy=github

**Comment by andrew** [comment]
Looks like it's a http/https mismatch, I've enabled `force_ssl` in production so everyone is on  https://contribulator.herokuapp.com now which should fix it.
