### ISSUE TITLE
Pagination looks bad when you have click through some pages.

### ISSUE THREAD

**Issue by frozzare** [andrew/contribulator#40]
The pagination looks bad when you have click through some pages.

![skarmklipp 2015-01-04 21 10 45](https://cloud.githubusercontent.com/assets/14610/5615920/ecedc9f4-94ff-11e4-928e-956f3106bd94.png)

**Comment by andrew** [comment]
cc @steverob as he added it in https://github.com/andrew/contribulator/pull/31
