### ISSUE TITLE
ActiveRecord::RecordNotFound when adding a new project

### ISSUE THREAD

**Issue by wadtech** [andrew/contribulator#43]
The explodeyness of `app/models/project.rb:27` causes the create project action to fail. It attempts to look up the project before creating it, which will raise.

In my opinion we should keep the previous behaviour and allow someone adding a project we already have to not be punished with an error page, it doesn't have any negative effect on the app itself.

**Comment by wadtech** [comment]
I can't find a better solution that to split the find into a normal and bang version so we can raise when we want the default behaviour and gracefully fall back to a create action if the project isn't already in the database.

could probably use a rescue in the controller but I'd rather avoid that personally.

**Comment by wadtech** [comment]
Closing this since the PR was merged.

**Comment by andrew** [comment]
Thanks @wadtech
